//
//  BlastAnalyzer.swift
//  blast_parser
//
//  Created by João Varela on 30/11/2024.
//

//import Foundation
//
//final class BlastAnalyzer: FileParser {
//    var asvs = [BlastASV]()
//    
//    /// Parses a BlastASV output as generated by BlastOutputParser,
//    /// which has the following layout:
//    /// - sequenceID:String         (KrakenASV)
//    /// - length:Int                (KrakenASV)
//    /// - assignedReads:Int         (KrakenASV)
//    /// - taxID:Int                 (KrakenASV)
//    /// - krakenTaxonomy:String     (KrakenASV)
//    /// - subjectSequenceID:Int     (BlastHit)
//    /// - percentageIdentity:Int    (BlastHit)
//    /// - bitscore:Int              (BlastHit)
//    /// - eValue:Double             (BlastHit)
//    /// - ncbiTaxID:Int             (BlastHit)
//    /// - scientificName:String     (BlastHit)
//    /// - blastTaxonomy:Hierarchy   (optional)
//    ///
//    /// krakenTaxonomy can be in two different formats:
//    /// - taxon:String (standard Kraken2 output format)
//    /// - hierarchy:String (Epi2Me Kraken2 output format)
//    func parse(asvFormat:ASVFormat) throws {
//        for line in readStream {
//            let asv = try BlastASV(line: line,
//                                   asvFormat: asvFormat)
//            asvs.append(asv)
//        }
//    }
//}
