//
//  KrakenASVParser.swift
//  blast_parser
//
//  Created by João Varela on 27/10/2024.
//

import Foundation

final class KrakenASVParser: FileParser {
    var binArray = KrakenASVBinArray()
    
    /// Parses the original ASV table as generated by Kraken2
    func parse() throws {
        var i = 1
        for line in readStream {
            do {
                let items = line.components(separatedBy: "\t")
                guard items.count == 5 else { throw RuntimeError("Invalid ASV file")}
                guard let taxonomy = KrakenASVTaxonomy(classification: items[2])
                    else { throw RuntimeError("ASV with invalid taxonomy")}
                let size = Int(items[3].trimmingCharacters(in: .whitespaces)) ?? 0
                let asv = KrakenASV(sequenceID: items[1],
                                    length: size,
                                    taxonomy: taxonomy)
                binArray.append(asv: asv)
            }
            
            i += 1
        }
        
        binArray.sort()
    }
}

